// Code generated by "grpc-kit-cli/0.5.1". DO NOT EDIT.

package handler

import (
    "context"

    pb "github.com/grpc-kit/testbed/api/known/testbed/v1"
    "github.com/grpc-kit/testbed/internal/security"
    "github.com/grpc-kit/testbed/public"
    "google.golang.org/grpc/health"
    "google.golang.org/grpc/health/grpc_health_v1"
)

// Register 用于服务启动前环境准备
func (m *Microservice) Register(ctx context.Context) error {
    pb.RegisterKnownTestbedServer(m.server.Server(), m)
    grpc_health_v1.RegisterHealthServer(m.server.Server(), health.NewServer())

    // 注册服务信息
    mux, err := m.baseCfg.Register(ctx, pb.RegisterKnownTestbedHandlerFromEndpoint)
    if err != nil {
        return err
    }

	// 注册访问安全策略
	if err = m.baseCfg.SecurityPolicyLoad(ctx, security.Assets); err != nil {
		return err
	}

    // 注册前端托管静态数据
    if err = m.baseCfg.HTTPHandlerFrontend(ctx, mux, public.Assets); err != nil {
        return err
    }

    // 这里添加其他自定义实现
    if err := m.privateHTTPHandle(mux); err != nil {
        return err
    }

    // 注册自定义 MCP 资源（Tools/Resources/Prompts，在 private.go 中实现）
    // 此时 HTTPHandlerFrontend 已同步完成 AutoBridge，自定义资源与 AutoBridge Tool 共存
    if err := m.privateMCPHandle(); err != nil {
        return err
    }

    // 注册HTTP网关
    if err := m.server.RegisterGateway(mux); err != nil {
        return err
    }

    // 开启gRPC与HTTP服务
    if err := m.server.StartBackground(ctx); err != nil {
        return err
    }

    return nil
}
