// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/known/testbed/v1/demo.proto

// 根据具体的微服务名称做更改

package testbedv1

import (
	v1 "github.com/grpc-kit/pkg/api/known/example/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DemoRequest Demo 方法请求可使用的接口参数
type DemoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID 资源编号
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Ping 资源内容
	Ping          *v1.ExampleRequest `protobuf:"bytes,2,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoRequest) Reset() {
	*x = DemoRequest{}
	mi := &file_api_known_testbed_v1_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoRequest) ProtoMessage() {}

func (x *DemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_known_testbed_v1_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoRequest.ProtoReflect.Descriptor instead.
func (*DemoRequest) Descriptor() ([]byte, []int) {
	return file_api_known_testbed_v1_demo_proto_rawDescGZIP(), []int{0}
}

func (x *DemoRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DemoRequest) GetPing() *v1.ExampleRequest {
	if x != nil {
		return x.Ping
	}
	return nil
}

// DemoResponse Demo方法响应的具体内容
type DemoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pong 返回创建的资源
	Pong *Pong `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	// Content 多个资源响应内容（无分页属性）
	Content []*v1.ExampleResponse `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	// Ping 返回更新的资源
	Ping *v1.ExampleResponse `protobuf:"bytes,3,opt,name=ping,proto3" json:"ping,omitempty"`
	// Empty 返回空的内容
	Empty         *emptypb.Empty `protobuf:"bytes,4,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoResponse) Reset() {
	*x = DemoResponse{}
	mi := &file_api_known_testbed_v1_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoResponse) ProtoMessage() {}

func (x *DemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_known_testbed_v1_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoResponse.ProtoReflect.Descriptor instead.
func (*DemoResponse) Descriptor() ([]byte, []int) {
	return file_api_known_testbed_v1_demo_proto_rawDescGZIP(), []int{1}
}

func (x *DemoResponse) GetPong() *Pong {
	if x != nil {
		return x.Pong
	}
	return nil
}

func (x *DemoResponse) GetContent() []*v1.ExampleResponse {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DemoResponse) GetPing() *v1.ExampleResponse {
	if x != nil {
		return x.Ping
	}
	return nil
}

func (x *DemoResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

var File_api_known_testbed_v1_demo_proto protoreflect.FileDescriptor

const file_api_known_testbed_v1_demo_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/known/testbed/v1/demo.proto\x12\x1cdefault.api.known.testbed.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a6github.com/grpc-kit/api/known/example/v1/example.proto\x1a.api/known/testbed/v1/microservice.common.proto\"d\n" +
	"\vDemoRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12A\n" +
	"\x04ping\x18\x02 \x01(\v2-.grpc_kit.api.known.example.v1.ExampleRequestR\x04ping\"\x82\x02\n" +
	"\fDemoResponse\x126\n" +
	"\x04pong\x18\x01 \x01(\v2\".default.api.known.testbed.v1.PongR\x04pong\x12H\n" +
	"\acontent\x18\x02 \x03(\v2..grpc_kit.api.known.example.v1.ExampleResponseR\acontent\x12B\n" +
	"\x04ping\x18\x03 \x01(\v2..grpc_kit.api.known.example.v1.ExampleResponseR\x04ping\x12,\n" +
	"\x05empty\x18\x04 \x01(\v2\x16.google.protobuf.EmptyR\x05emptyB<Z:github.com/grpc-kit/testbed/api/known/testbed/v1;testbedv1b\x06proto3"

var (
	file_api_known_testbed_v1_demo_proto_rawDescOnce sync.Once
	file_api_known_testbed_v1_demo_proto_rawDescData []byte
)

func file_api_known_testbed_v1_demo_proto_rawDescGZIP() []byte {
	file_api_known_testbed_v1_demo_proto_rawDescOnce.Do(func() {
		file_api_known_testbed_v1_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_known_testbed_v1_demo_proto_rawDesc), len(file_api_known_testbed_v1_demo_proto_rawDesc)))
	})
	return file_api_known_testbed_v1_demo_proto_rawDescData
}

var file_api_known_testbed_v1_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_known_testbed_v1_demo_proto_goTypes = []any{
	(*DemoRequest)(nil),        // 0: default.api.known.testbed.v1.DemoRequest
	(*DemoResponse)(nil),       // 1: default.api.known.testbed.v1.DemoResponse
	(*v1.ExampleRequest)(nil),  // 2: grpc_kit.api.known.example.v1.ExampleRequest
	(*Pong)(nil),               // 3: default.api.known.testbed.v1.Pong
	(*v1.ExampleResponse)(nil), // 4: grpc_kit.api.known.example.v1.ExampleResponse
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_api_known_testbed_v1_demo_proto_depIdxs = []int32{
	2, // 0: default.api.known.testbed.v1.DemoRequest.ping:type_name -> grpc_kit.api.known.example.v1.ExampleRequest
	3, // 1: default.api.known.testbed.v1.DemoResponse.pong:type_name -> default.api.known.testbed.v1.Pong
	4, // 2: default.api.known.testbed.v1.DemoResponse.content:type_name -> grpc_kit.api.known.example.v1.ExampleResponse
	4, // 3: default.api.known.testbed.v1.DemoResponse.ping:type_name -> grpc_kit.api.known.example.v1.ExampleResponse
	5, // 4: default.api.known.testbed.v1.DemoResponse.empty:type_name -> google.protobuf.Empty
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_known_testbed_v1_demo_proto_init() }
func file_api_known_testbed_v1_demo_proto_init() {
	if File_api_known_testbed_v1_demo_proto != nil {
		return
	}
	file_api_known_testbed_v1_microservice_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_known_testbed_v1_demo_proto_rawDesc), len(file_api_known_testbed_v1_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_known_testbed_v1_demo_proto_goTypes,
		DependencyIndexes: file_api_known_testbed_v1_demo_proto_depIdxs,
		MessageInfos:      file_api_known_testbed_v1_demo_proto_msgTypes,
	}.Build()
	File_api_known_testbed_v1_demo_proto = out.File
	file_api_known_testbed_v1_demo_proto_goTypes = nil
	file_api_known_testbed_v1_demo_proto_depIdxs = nil
}
