// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/known/testbed/v1/microservice.common.proto

// 根据具体的微服务名称做更改

package testbedv1

import (
	v1 "github.com/grpc-kit/pkg/api/known/example/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pong struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID 资源编号
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Pong 单个资源响应内容
	Pong          *v1.ExampleResponse    `protobuf:"bytes,2,opt,name=pong,proto3" json:"pong,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_api_known_testbed_v1_microservice_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_api_known_testbed_v1_microservice_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_api_known_testbed_v1_microservice_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pong) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Pong) GetPong() *v1.ExampleResponse {
	if x != nil {
		return x.Pong
	}
	return nil
}

func (x *Pong) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Pong) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_known_testbed_v1_microservice_common_proto protoreflect.FileDescriptor

const file_api_known_testbed_v1_microservice_common_proto_rawDesc = "" +
	"\n" +
	".api/known/testbed/v1/microservice.common.proto\x12\x1cdefault.api.known.testbed.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a6github.com/grpc-kit/api/known/example/v1/example.proto\"\xd4\x01\n" +
	"\x04Pong\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12B\n" +
	"\x04pong\x18\x02 \x01(\v2..grpc_kit.api.known.example.v1.ExampleResponseR\x04pong\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB<Z:github.com/grpc-kit/testbed/api/known/testbed/v1;testbedv1b\x06proto3"

var (
	file_api_known_testbed_v1_microservice_common_proto_rawDescOnce sync.Once
	file_api_known_testbed_v1_microservice_common_proto_rawDescData []byte
)

func file_api_known_testbed_v1_microservice_common_proto_rawDescGZIP() []byte {
	file_api_known_testbed_v1_microservice_common_proto_rawDescOnce.Do(func() {
		file_api_known_testbed_v1_microservice_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_known_testbed_v1_microservice_common_proto_rawDesc), len(file_api_known_testbed_v1_microservice_common_proto_rawDesc)))
	})
	return file_api_known_testbed_v1_microservice_common_proto_rawDescData
}

var file_api_known_testbed_v1_microservice_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_known_testbed_v1_microservice_common_proto_goTypes = []any{
	(*Pong)(nil),                  // 0: default.api.known.testbed.v1.Pong
	(*v1.ExampleResponse)(nil),    // 1: grpc_kit.api.known.example.v1.ExampleResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_known_testbed_v1_microservice_common_proto_depIdxs = []int32{
	1, // 0: default.api.known.testbed.v1.Pong.pong:type_name -> grpc_kit.api.known.example.v1.ExampleResponse
	2, // 1: default.api.known.testbed.v1.Pong.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: default.api.known.testbed.v1.Pong.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_known_testbed_v1_microservice_common_proto_init() }
func file_api_known_testbed_v1_microservice_common_proto_init() {
	if File_api_known_testbed_v1_microservice_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_known_testbed_v1_microservice_common_proto_rawDesc), len(file_api_known_testbed_v1_microservice_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_known_testbed_v1_microservice_common_proto_goTypes,
		DependencyIndexes: file_api_known_testbed_v1_microservice_common_proto_depIdxs,
		MessageInfos:      file_api_known_testbed_v1_microservice_common_proto_msgTypes,
	}.Build()
	File_api_known_testbed_v1_microservice_common_proto = out.File
	file_api_known_testbed_v1_microservice_common_proto_goTypes = nil
	file_api_known_testbed_v1_microservice_common_proto_depIdxs = nil
}
