// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/known/testbed/v1/microservice.proto

package testbedv1

import (
	context "context"
	v1 "github.com/grpc-kit/pkg/api/known/status/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnownTestbed_HealthCheck_FullMethodName = "/default.api.known.testbed.v1.KnownTestbed/HealthCheck"
	KnownTestbed_Demo_FullMethodName        = "/default.api.known.testbed.v1.KnownTestbed/Demo"
)

// KnownTestbedClient is the client API for KnownTestbed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 该微服务支持的 RPC 方法定义
type KnownTestbedClient interface {
	// 内置服务，健康检查
	HealthCheck(ctx context.Context, in *v1.HealthCheckRequest, opts ...grpc.CallOption) (*v1.HealthCheckResponse, error)
	// 示例实现，可以删除
	Demo(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error)
}

type knownTestbedClient struct {
	cc grpc.ClientConnInterface
}

func NewKnownTestbedClient(cc grpc.ClientConnInterface) KnownTestbedClient {
	return &knownTestbedClient{cc}
}

func (c *knownTestbedClient) HealthCheck(ctx context.Context, in *v1.HealthCheckRequest, opts ...grpc.CallOption) (*v1.HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.HealthCheckResponse)
	err := c.cc.Invoke(ctx, KnownTestbed_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knownTestbedClient) Demo(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DemoResponse)
	err := c.cc.Invoke(ctx, KnownTestbed_Demo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnownTestbedServer is the server API for KnownTestbed service.
// All implementations should embed UnimplementedKnownTestbedServer
// for forward compatibility.
//
// 该微服务支持的 RPC 方法定义
type KnownTestbedServer interface {
	// 内置服务，健康检查
	HealthCheck(context.Context, *v1.HealthCheckRequest) (*v1.HealthCheckResponse, error)
	// 示例实现，可以删除
	Demo(context.Context, *DemoRequest) (*DemoResponse, error)
}

// UnimplementedKnownTestbedServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnownTestbedServer struct{}

func (UnimplementedKnownTestbedServer) HealthCheck(context.Context, *v1.HealthCheckRequest) (*v1.HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedKnownTestbedServer) Demo(context.Context, *DemoRequest) (*DemoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Demo not implemented")
}
func (UnimplementedKnownTestbedServer) testEmbeddedByValue() {}

// UnsafeKnownTestbedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnownTestbedServer will
// result in compilation errors.
type UnsafeKnownTestbedServer interface {
	mustEmbedUnimplementedKnownTestbedServer()
}

func RegisterKnownTestbedServer(s grpc.ServiceRegistrar, srv KnownTestbedServer) {
	// If the following call panics, it indicates UnimplementedKnownTestbedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnownTestbed_ServiceDesc, srv)
}

func _KnownTestbed_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnownTestbedServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnownTestbed_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnownTestbedServer).HealthCheck(ctx, req.(*v1.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnownTestbed_Demo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnownTestbedServer).Demo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnownTestbed_Demo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnownTestbedServer).Demo(ctx, req.(*DemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnownTestbed_ServiceDesc is the grpc.ServiceDesc for KnownTestbed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnownTestbed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "default.api.known.testbed.v1.KnownTestbed",
	HandlerType: (*KnownTestbedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _KnownTestbed_HealthCheck_Handler,
		},
		{
			MethodName: "Demo",
			Handler:    _KnownTestbed_Demo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/known/testbed/v1/microservice.proto",
}
