// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/known/testbed/v1/microservice.proto

package testbedv1

import (
	v1 "github.com/grpc-kit/pkg/api/known/status/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_known_testbed_v1_microservice_proto protoreflect.FileDescriptor

const file_api_known_testbed_v1_microservice_proto_rawDesc = "" +
	"\n" +
	"'api/known/testbed/v1/microservice.proto\x12\x1cdefault.api.known.testbed.v1\x1a\x1fapi/known/testbed/v1/demo.proto\x1a6github.com/grpc-kit/api/known/status/v1/response.proto2\xe5\x01\n" +
	"\fKnownTestbed\x12t\n" +
	"\vHealthCheck\x120.grpc_kit.api.known.status.v1.HealthCheckRequest\x1a1.grpc_kit.api.known.status.v1.HealthCheckResponse\"\x00\x12_\n" +
	"\x04Demo\x12).default.api.known.testbed.v1.DemoRequest\x1a*.default.api.known.testbed.v1.DemoResponse\"\x00B<Z:github.com/grpc-kit/testbed/api/known/testbed/v1;testbedv1b\x06proto3"

var file_api_known_testbed_v1_microservice_proto_goTypes = []any{
	(*v1.HealthCheckRequest)(nil),  // 0: grpc_kit.api.known.status.v1.HealthCheckRequest
	(*DemoRequest)(nil),            // 1: default.api.known.testbed.v1.DemoRequest
	(*v1.HealthCheckResponse)(nil), // 2: grpc_kit.api.known.status.v1.HealthCheckResponse
	(*DemoResponse)(nil),           // 3: default.api.known.testbed.v1.DemoResponse
}
var file_api_known_testbed_v1_microservice_proto_depIdxs = []int32{
	0, // 0: default.api.known.testbed.v1.KnownTestbed.HealthCheck:input_type -> grpc_kit.api.known.status.v1.HealthCheckRequest
	1, // 1: default.api.known.testbed.v1.KnownTestbed.Demo:input_type -> default.api.known.testbed.v1.DemoRequest
	2, // 2: default.api.known.testbed.v1.KnownTestbed.HealthCheck:output_type -> grpc_kit.api.known.status.v1.HealthCheckResponse
	3, // 3: default.api.known.testbed.v1.KnownTestbed.Demo:output_type -> default.api.known.testbed.v1.DemoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_known_testbed_v1_microservice_proto_init() }
func file_api_known_testbed_v1_microservice_proto_init() {
	if File_api_known_testbed_v1_microservice_proto != nil {
		return
	}
	file_api_known_testbed_v1_demo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_known_testbed_v1_microservice_proto_rawDesc), len(file_api_known_testbed_v1_microservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_known_testbed_v1_microservice_proto_goTypes,
		DependencyIndexes: file_api_known_testbed_v1_microservice_proto_depIdxs,
	}.Build()
	File_api_known_testbed_v1_microservice_proto = out.File
	file_api_known_testbed_v1_microservice_proto_goTypes = nil
	file_api_known_testbed_v1_microservice_proto_depIdxs = nil
}
